/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package practica0

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    var productos=ArrayList<Producto>()
    productos.add(Producto("Lavadora grande",345f
    ,"lg.jpeg","lavadora grande",Estado.ACTIVO))

    productos.add(Producto("Televisor 55\"",545f
    ,"tv55.jpeg","televisor grande",Estado.ACTIVO))

    productos.add(Producto("Portatil 14",654f
    ,"ptt.jpeg","portatil de 8gb pequeño",Estado.ACTIVO))
}

